import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from '@src/app/modules/app-routing/app-routing.module';
import { AppComponent } from '@src/app/components/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { HomeComponent } from '@src/app/components/home/home.component';
import { HeaderComponent } from '@src/app/components/header/header.component';
import { FooterComponent } from '@src/app/components/footer/footer.component';
import { ModulesComponent } from '@src/app/components/modules/modules.component';
import { ModulePageComponent } from '@src/app/components/module-page/module-page.component';
import { ModuleEditComponent } from '@src/app/components/module-edit/module-edit.component';
import { ModuleCardComponent } from '@src/app/components/module-card/module-card.component';
import { EditTitleComponent } from '@src/app/components/edit/edit-title/edit-title.component';
import { EditParagraphComponent } from '@src/app/components/edit/edit-paragraph/edit-paragraph.component';
import { EditActivityComponent } from '@src/app/components/edit/edit-activity/edit-activity.component';
import { EditModuleInfoComponent } from '@src/app/components/edit/edit-module-info/edit-module-info.component';
import { EditImageComponent } from '@src/app/components/edit/edit-image/edit-image.component';
import { EditYoutubeComponent } from '@src/app/components/edit/edit-youtube/edit-youtube.component';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    HomeComponent,
    HeaderComponent,
    FooterComponent,
    ModulesComponent,
    ModulePageComponent,
    ModuleEditComponent,
    ModuleCardComponent,
    EditTitleComponent,
    EditParagraphComponent,
    EditActivityComponent,
    EditModuleInfoComponent,
    EditImageComponent,
    EditYoutubeComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    NgbModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
