export const errors = {
    AuthenticatorError:{
        AUTHENTICATION_FAILED: 'Error al iniciar sesión. ¿Introdujo su correo electrónico y contraseña correctamente?',
        NOT_AUTHENTICATED: 'Debe iniciar sesión para acceder a estas funcionalidad.',
        USER_NOT_ADMINISTRATOR: 'Esta funcionalidad es exclusiva para administradores.',
        USER_NOT_EDUCATOR: 'Esta funcionalidad es exclusiva para educadores ambientales.',
        INVALID_PASSWORD: 'Contraseña incorrecta.',
        USER_ROLE_COULD_NOT_BE_RESOLVED: 'No se pudo resolver el tipo de usuario al iniciar sesión. Esto usualmente es un error interno y debería reportarlo.',
        REAUTHENTICATION_REQUIRED: 'Por motivos de seguridad, esta operación requiere que reinicie sesión en este dispositivo.',
    },
    DatabaseError:{
        DISCIPLINE_METADATA_NOT_FOUND: 'La información de disciplinas posibles para implementables no pudo ser encontrada.',
        USER_NOT_FOUND: 'La información asociada a esta cuenta de usuario no pudo ser encontrada.',
        USER_ALREADY_EXISTS: 'Ya existe una cuenta de usuario con ese correo electrónico. Por favor intente otro correo electrónico.',
        EDUCATOR_REQUEST_NOT_FOUND: 'No se pudo encontrar la solicitud de educador ambiental selecconada.',
        EDUCATOR_REQUEST_ALREADY_PENDING: 'Ya existe una solicitud pendiente con ese correo electrónico. Por favor intente con otro o comuníquese directamente con un administrador para que acepten o rechacen la solicitud existente.',
        UNKNOWN_IMPLEMENTABLE_TYPE: 'Tipo de implementable desconocido. Esto usualmente es un error interno y debería reportarlo.',
        IMPLEMENTABLE_NOT_FOUND: 'No se pudo encontrar el implementable seleccionado.',
        SECTION_NOT_FOUND: 'No se pudo encontrar la sección seleccionada.',
        FILE_NOT_FOUND: 'No se pudo encontrar la información del archivo seleccionado.',
        QUESTION_NOT_FOUND: 'No se pudo encontrar la pregunta seleccionada.',
        IMPLEMENTATION_NOT_FOUND: 'No se pudo encontrar la implementación seleccionada.',
        IMPLEMENTATION_IS_COMPLETE: 'No se puede editar esta implementación dado a que está completa.',
        ANSWER_NOT_FOUND: 'No se pudo encontrar la respuesta a la evaluación seleccionada.',
        EVIDENCE_NOT_FOUND: 'No se pudo encontrar la información del archivo de evidencia seleccionado.',
        ALLY_NOT_FOUND: 'No se pudo encontrar la información del aliado estratégico seleccionado.',
    },
    FactoryError:{
        UNKNOWN_IUSER: 'Tipo de usuario interno desconocido. Esto usualmente es un error interno y debería reportarlo.',
        UNKNOWN_ISECTION: 'Tipo de sección interno desconocido. Esto usualmente es un error interno y debería reportarlo.',
        UNKNOWN_IIMPLEMENTABLE: 'Tipo de implementable interno desconocido. Esto usualmente es un error interno y debería reportarlo.'
    },
    ValidatorError:{
        IS_NULL_OR_UNDEFINED: '',
        HAS_NULL_OR_UNDEFINED_FIELDS: 'Debe incluir toda la información pedida para completar la operación.',
        RUNTIME_ERROR: 'Error imprevisto interno de ejecución. Por favor repórtelo a un administrador.',
        MALFORMED_COLOR: 'Código de color incorrecto. El formato es #XXYYZZ; donde X, Y y Z son números o letras de la A a la F.',
        MALFORMED_URL: 'URL incorrecto. Por favor introduzca un URL válido.',
        MALFORMED_EMAIL: 'Email incorrecto. Por favor introduzca una dirección de correo electrónica válida.',
        MALFORMED_PHONE: 'Número de teléfono incorrecto. Por favor introduzca un número telefónico con únicamente 8 dígitos, sin espacios ni guinoes.',
        RECOMMENDED_AGE_LESS_THAN_ZERO: 'La edad recomendada no puede ser menor a 0.',
        RECOMMENDED_AGE_NOT_WHOLE_NUMBER: 'La edad recomendada debe ser un número entero.',
        PARTICIPANTS_LESS_THAN_ZERO: 'La cantidad de participantes no puede ser un número menor a 0.',
        BYTES_LESS_THAN_ZERO: 'La cantidad de bytes para el archivo o evidencia no puede ser menor a 0.',
        INDEX_LESS_THAN_ZERO: 'El índice para el orden de la sección no puede ser menor.',
        ESTIMATED_MINUTES_LESS_THAN_ZERO: 'La cantidad de minutos estimados para la actividad no puede ser menor a 0.',
        EMPTY_PUBLISHER_ID: 'El implementable no tiene un identificador del administrador que lo creó asociado. Esto usualmente es un error interno y debería reportarlo.',
        JOINED_CANT_BE_FUTURE: 'La fecha de afiliación del educador ambiental no puede estar en el futuro. Esto usualmente es un error interno y debería ser reportado.',
        UPLOADED_CANT_BE_FUTURE: 'La fecha de subida del archivo o evidencia no puede estar en el futuro. Esto usualmente es un error interno y debería ser reportado.',
        BIRTHDAY_CANT_BE_FUTURE: 'La fecha de cumpleaños no puede estar en el futuro.',
        IMPLEMENTATION_DATE_CANT_BE_FUTURE: 'La fecha de la implementación no puede estar en el futuro.',
        DATE_CANT_BE_PAST: 'La fecha agregada no puede estar en el pasado.',
        UNKNOWN_IUSER: 'Tipo de usuario interno desconocido. Esto usualmente es un error interno y debería reportarlo.',
        UNKNOWN_ISECTION: 'Tipo de sección interno desconocido. Esto usualmente es un error interno y debería reportarlo.',
        UNKNOWN_IIMPLEMENTABLE: 'Tipo de implementable interno desconocido. Esto usualmente es un error interno y debería reportarlo.',
        LATITUDE_OUT_OF_BOUNDS: 'Latitud fuera del rango esperado. La latitud es únicamente un valor entre -90 y 90.',
        LONGITUDE_OUT_OF_BOUNDS: 'Longitud fuera del rango esperado. La longitud es únicamente un valor entre -180 y 180.'
    },
    StorageError:{
        UPLOAD_ERROR: "Ha ocurrido un error subiendo un archivo.",
        DELETE_ERROR: "Ha ocurrido un error borrando un archivo."
    },
    ControllerError:{}
}